### ISSUE TITLE
[evaluation] Autocertificazione voto 2019

### ISSUE THREAD

**Issue by f-cazzola** [S0NN1/progetto-ing-sw-polimi#8]
Certifico che il progetto in 2019 - other avente come repo https://github.com/f-cazzola/ing-sw-2019-bordoni-cazzola-dotti è stato valutato 30 dal buon Margara.

**Comment by f-cazzola** [comment]
Aggiungere la label sfortunatamente non è possibile, credo lo sia solo al proprietario della repo.

**Comment by S0NN1** [comment]
Si grazie ho notato solo ora che Github non permette se non si usano i templates. Li sto creando così che le future issues siano standardizzate. Grazie per la precisazione!
